<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5VGD0PP" failures="0" tests="3" name="TestNgCommands.TestNgcomands" time="0.034" errors="1" timestamp="2024-12-03T05:53:35 IST" skipped="1">
  <testcase classname="TestNgCommands.TestNgcomands" name="testcase2" time="0.010"/>
  <testcase classname="TestNgCommands.TestNgcomands" name="testcase3" time="0.024">
    <error message="Method TestNgCommands.TestNgcomands.testcase3() didn&#039;t finish within the time-out 10" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNgCommands.TestNgcomands.testcase3() didn't finish within the time-out 10
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at TestNgCommands.TestNgcomands.testcase3(TestNgcomands.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- testcase3 -->
  <testcase classname="TestNgCommands.TestNgcomands" name="testcase1">
    <skipped/>
  </testcase> <!-- testcase1 -->
</testsuite> <!-- TestNgCommands.TestNgcomands -->
